server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/merchant_assistant?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
#开启驼峰命名转换
mybatis:
  configuration:
    map-underscore-to-camel-case: true
weChat:
  appId: wx069b7dc66afc066d
  appSecret: 4b80b43c0ea1e3ede324f7f57df22dd6
file:
  imgPath: E:\\resources\\images\\
header:
  origin: http://localhost:8080


